run:
  timeout: 5m
  tests: true
  skip-dirs-use-default: true

output:
  formats:
    - format: colored-line-number

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
  disable:
    - structcheck
    - varcheck
    - deadcode

linters-settings:
  errcheck:
    check-blank: false
    exclude-functions:
      - fmt.Fprintf
      - fmt.Fprintln
      - (*os.File).Close
      - (*os.File).Sync

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - unused
    - path: (vendor|docs|ml)/
      linters:
        - all
    - text: "Error return value is not checked"
      linters:
        - errcheck
    - text: "is unused"
      linters:
        - unused
  max-issues-per-linter: 50
  max-same-issues: 10
